services:
  redis:
    image: redis:7-alpine
    container_name: awilixify-fastify-cqrs-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis_data:/data

volumes:
  redis_data:
